### ISSUE TITLE
Is it possible to get the position of the text cursor?

### ISSUE THREAD

**Issue by GanZhiXiong** [godbout/AXBugsWithCatalystApps#1]
I tried a lot of code without success, looking forward to your reply. thank you very much!

**Comment by godbout** [comment]
not sure if it's possible. but what you can get is the bounds of the selection. have a look at https://developer.apple.com/documentation/applicationservices/kaxboundsforrangeparameterizedattribute#

**Comment by GanZhiXiong** [comment]
@godbout 

Use the following code to get the cursor of the browser input box and vscode, while other apps need to select the text to get it.
Is there a way to get the cursor without selecting the text?

``` swift
        let timer = Timer.scheduledTimer(
                withTimeInterval: 2.0,
                repeats: true
        ) { (_: Timer) in
            let systemWideElement = AXUIElementCreateSystemWide()
            var focusedElement : AnyObject?

            let error = AXUIElementCopyAttributeValue(systemWideElement, kAXFocusedUIElementAttribute as CFString, &focusedElement)
            if (error != .success){
                print("Couldn't get the focused element. Probably a webkit application")
            } else {
                var selectedRangeValue : AnyObject?
                let selectedRangeError = AXUIElementCopyAttributeValue(focusedElement as! AXUIElement, kAXSelectedTextRangeAttribute as CFString, &selectedRangeValue)
                if (selectedRangeError == .success){
                    var selectedRange : CFRange?
                    AXValueGetValue(selectedRangeValue as! AXValue, AXValueType(rawValue: kAXValueCFRangeType)!, &selectedRange)
                    var selectRect = CGRect()
                    var selectBounds : AnyObject?
                    let selectedBoundsError = AXUIElementCopyParameterizedAttributeValue(focusedElement as! AXUIElement, kAXBoundsForRangeParameterizedAttribute as CFString, selectedRangeValue!, &selectBounds)
                    if (selectedBoundsError == .success){
                        AXValueGetValue(selectBounds as! AXValue, .cgRect, &selectRect)
                        //do whatever you want with your selectRect
                        print("selectRect", selectRect)
                    }
                }
            }
        }

        timer.fire()
```

**Comment by GanZhiXiong** [comment]
@godbout 

I think one way is to select the text or generate a space through code, and then get the position of the cursor, but this will affect the visual effect.

It seems difficult to achieve.

**Comment by godbout** [comment]
tbh i'm not even sure what i'm talking about. this repo here is for Apple, so that they can reproduce bugs that happen in Catalyst apps. i don't think this has anything to do with getting the caret location. but maybe i'm wrong. i don't remember. i moved on.

in my own app [kindaVim](https://github.com/godbout/kindaVim.docs) i draw a window on top of the caret, but when it's selected only. so i have no idea how to get the caret position when at least one character is not selected. maybe it works without the selection. but even if it does, it'll probably fail with lots of apps. the AX APIs are capricious. (actually not the APIs themselves, more like there's a huge number of shit apps that implement things like shit.)

good luck.

**Comment by GanZhiXiong** [comment]
Thanks for helping me analyze it, it doesn't look that easy, but I'll keep researching.

Your app KV is so cool, being able to use KV anywhere is really a benefit for vim users, and using KV no longer needs to install various vim plugins for ide, very good, great👍👍👍

**Comment by godbout** [comment]
> Thanks for helping me analyze it, it doesn't look that easy, but I'll keep researching.

sure no worries. let me know if you find something. here's a SO answer, but it seems the same as what i told you. need the bounds of the caret: ≤https://stackoverflow.com/questions/25610607/how-to-find-the-blinking-cursor-location-of-any-active-application

> Your app KV is so cool, being able to use KV anywhere is really a benefit for vim users, and using KV no longer needs to install various vim plugins for ide, very good, great👍👍👍

glad it helps! almost two years full-time now. still a lot to do. but i would think that usually Vim plugins in IDEs are better, as they usually have access to the app's buffer itself. i only use Sublime Text myself out of Xcode, and i use the NeoVintageous plugin, not kV :p

**Comment by GanZhiXiong** [comment]
KV is great, there are very few softwares like this.

**Whether it can be submitted to the App Store?**. 
 it is easy to promote and users can use it with confidence.

**Comment by godbout** [comment]
> KV is great, there are very few softwares like this.

nobody is dumb enough to build something like this 😂️😂️😂️ it's a huge amount of unstable work. very small ROI. the niche of users is very narrow. but i need it for myself so...

> **Whether it can be submitted to the App Store?**. it is easy to promote and users can use it with confidence.

i would **LOVE** to have it on the App Store. not for the number of users. as said, the niche is very narrow anyways. but i'd give Apple 30% to handle payments, licenses, subscriptions etc. i hate working on those. massive pain. very boring. but kV cannot be on the App Store. the App Store now only allows sandboxed app (since 2012). that means you can't touch anything else other than yourself, and you can't use the Accessibility APIs. as long as they don't change this (i don't think they will), kV needs to be outside the Store ☹️

**Comment by GanZhiXiong** [comment]
> App Store now only allows sandboxed app (since 2012)

Apple restricts, then there is no way, it is a pity.

If it can't be put on the App Store, is the app easy to be cracked, it seems that the apk on the App Store is encrypted, it is not so easy to crack, and I am not very clear.
For example, at http://macwk.com/ you can download almost any app that you need to pay for.

So you may need to do something to prevent the app from being cracked

**Comment by godbout** [comment]
people can crack, no problem. i don't care. kV costs 3US a month. it's cheap. i'm not gonna beg and run after people who don't wanna pay. not my problem. i have more important things to do with my time and energy, like building awesome apps. people want to crack? their responsibilities. hope they sleep well at night.

**Comment by GanZhiXiong** [comment]
> have more important things to do with my time and energy, like building awesome apps.

👍👍👍

**Comment by GanZhiXiong** [comment]
@godbout 
Excuse me again, you are familiar with the Accessibility API, so I want to ask you:
How to get the specified range of text? For example, what is the first character to the right of the cursor?
The following code is the range where I get the first character to the right of the cursor. How to get the text of this range?

``` swift
        let axApp = AXUIElementCreateApplication(app.processIdentifier)
        var focusedElement: CFTypeRef?
        guard
                AXUIElementCopyAttributeValue(axApp, kAXFocusedUIElementAttribute as CFString, &focusedElement)
                        == .success
        else {
            return nil
        }
        var selectedRangeValue: CFTypeRef?
        guard AXUIElementCopyAttributeValue(focusedElement as! AXUIElement, kAXSelectedTextRangeAttribute as CFString, &selectedRangeValue) == .success else {
            return nil
        }

        var selectedRange: CFRange = .init(location: 0, length: 0)
        AXValueGetValue(selectedRangeValue as! AXValue, AXValueType.cfRange, &selectedRange)
        selectedRange = .init(location: selectedRange.location + 1, length: selectedRange.length + 1)
```

**Comment by godbout** [comment]
hmm if i get you correctly, this is not related to the AX APIs, this is about Swift Strings: https://developer.apple.com/documentation/swift/string#

you need to check the `index` functions. Strings don't use Int locations, they use Index, because of Unicode. in your code the `selectedRange.location + 1` and `length + 1` are gonna fail with emojis. an emoji may be 2, 3, 5, 7, etc. characters length in UTF-8, that is what the AX API returns. but in Swift String they're all be equal to 1. so you need to convert, etc.

most probably what you're gonna have to do is build a lot of wrapper so that you can get the characters, or substring, of a range.

**Comment by godbout** [comment]
check all the `index` functions. pass your range to them, and get the substring. then you'll get what you need. good luck.

**Comment by GanZhiXiong** [comment]
I forgot to reply, thank you very much for your patience!

**Comment by GanZhiXiong** [comment]
Do you know how to get the size of the text cursor? There seems to be no such API

**Comment by godbout** [comment]
what do you mean? the text size in points? the width and height of the cursor itself? again, i have no idea about the cursor. all i know is the selected box. the API for the box is what i gave above, the AXParam shit.

**Comment by godbout** [comment]
maybe have a look at Vimac's source? https://github.com/dexterleng/vimac
the app hides the cursor sometimes. probably nothing to do with getting the size or whatever, but maybe the APIs are related? no idea. you're gonna have to do your own research.
